### ISSUE TITLE
Road to Spring I/O checklist

### ISSUE THREAD

**Issue by salaboy** [diagridio/dapr-spring-boot-starter#23]
Working on the `new-spring-boot` branch, we should get the following items done to showcase this work at Spring I/O by the end of May.

- [x] KeyValueTemplate using Dapr APIs @salaboy 
  - [x] Cover basic query capabilities 
- [x] MessagingTemplate using Dapr APIs @salaboy 
- [x] Dapr Testcontainers release with dependsOn (network and placement) released @salaboy 
- [ ] Release dapr-spring-boot-starter modules or build from source 
- [x] Update example https://github.com/salaboy/example-voting-app with:
  - [x] Java Worker @salaboy  
  - [x] Java Results @salaboy 
  - [x] Update Echo to use new subscription @salaboy 
  - [ ] Update Vote to use new KeyValueTemplate implementation @salaboy 

- [ ] Compile Echo to use native images @ThomasVitale 
- [ ] Release new native images to github container registry
- [x] Review @salaboy Spring boot code by @ThomasVitale

**Comment by ThomasVitale** [comment]
Some more tasks:

- [ ] Support configuring DaprClient via application properties instead of environment variables/JVM System properties
- [ ] Enhance Dapr Client Spring Boot Starter with configuration properties and service connections
- [ ] Configure service connections in Testcontainers for Dapr Client
- [ ] Configure service binding for Dapr Client

**Comment by salaboy** [comment]
there are still some open tasks here, but new issues will be created.
